name: education_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^0.13.1
  flutter_icons: ^0.1.4
  cached_network_image: ^1.1.1


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/study.svg
    - lib/assets/images/design-tool.svg
    - lib/assets/images/dna.svg
    - lib/assets/images/flask.svg
    - lib/assets/images/microscope.svg
    - lib/assets/images/bookmark.svg
    - lib/assets/images/notification.svg
    - lib/assets/images/home.svg
    - lib/assets/images/controls.svg
    - lib/assets/images/user.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: pop
      fonts:
        - asset: lib/assets/fonts/Poppins-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/Poppins-Light.otf
          weight: 300
        - asset: lib/assets/fonts/Poppins-ExtraLight.otf
          weight: 200
        - asset: lib/assets/fonts/Poppins-Thin.otf
          weight: 100
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
